### ISSUE TITLE
#####panic: runtime error: index out of range

### ISSUE THREAD

**Issue by rmoff** [adejoux/nmon2influxdb#13]
```
    ec2-user@controller:nmon () $ ./nmon2influxdb-linux-amd64 -v
    nmon2influxdb version 0.6.0

    ec2-user@controller:nmon () $ ./nmon2influxdb-linux-amd64 --debug --server localhost --port 8086 --db nmon import demo.us.oracle.com-2015-11-30-103927.nmon
    ADDING serie CPU_ALL
    ADDING serie MEM
    ADDING serie PROC
    ADDING serie NET
    ADDING serie NETPACKET
    ADDING serie DISKBUSY
    ADDING serie DISKREAD
    ADDING serie DISKWRITE
    ADDING serie DISKXFER
    ADDING serie DISKBSIZE
    ADDING serie JFSFILE
    ERROR: parsing the following line : TOP,%CPU Utilisation
    ADDING serie TOP
    ADDING serie VM
    time : 991.224µs, version : 0.9.5.1
    [{[{databases map[] [name] [[graphite] [_internal] [obi] [nmon]] <nil>}] <nil>}]
    #####panic: runtime error: index out of range

    goroutine 1 [running]:
    main.NmonImport(0xc208001200)
            /go/src/github.com/adejoux/nmon2influxdb/nmon_importer.go:145 +0x1988
    github.com/adejoux/nmon2influxdb/Godeps/_workspace/src/github.com/codegangsta/cli.Command.Run(0x7f25f0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x82c0b0, 0x12, 0x0, ...)
            /go/src/github.com/adejoux/nmon2influxdb/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:131 +0x1001
    github.com/adejoux/nmon2influxdb/Godeps/_workspace/src/github.com/codegangsta/cli.(*App).Run(0xc208000ea0, 0xc20800a000, 0xa, 0xa, 0x0, 0x0)
            /go/src/github.com/adejoux/nmon2influxdb/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:175 +0x1184
    main.main()
            /go/src/github.com/adejoux/nmon2influxdb/main.go:207 +0x2311

    goroutine 13 [select]:
    net/http.(*persistConn).writeLoop(0xc20807a630)
            /usr/src/go/src/net/http/transport.go:945 +0x41d
    created by net/http.(*Transport).dialConn
            /usr/src/go/src/net/http/transport.go:661 +0xcbc

    goroutine 12 [IO wait]:
    net.(*pollDesc).Wait(0xc20827d870, 0x72, 0x0, 0x0)
            /usr/src/go/src/net/fd_poll_runtime.go:84 +0x47
    net.(*pollDesc).WaitRead(0xc20827d870, 0x0, 0x0)
            /usr/src/go/src/net/fd_poll_runtime.go:89 +0x43
    net.(*netFD).Read(0xc20827d810, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7f20734efc30, 0xc208c5c5b8)
            /usr/src/go/src/net/fd_unix.go:242 +0x40f
    net.(*conn).Read(0xc20802e098, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
            /usr/src/go/src/net/net.go:121 +0xdc
    net/http.noteEOFReader.Read(0x7f20734f1fd0, 0xc20802e098, 0xc20807a688, 0xc20800f000, 0x1000, 0x1000, 0xc208461f00, 0x0, 0x0)
            /usr/src/go/src/net/http/transport.go:1270 +0x6e
    net/http.(*noteEOFReader).Read(0xc208d41d40, 0xc20800f000, 0x1000, 0x1000, 0xc208012000, 0x0, 0x0)
            <autogenerated>:125 +0xd4
    bufio.(*Reader).fill(0xc20827bf80)
            /usr/src/go/src/bufio/bufio.go:97 +0x1ce
    bufio.(*Reader).Peek(0xc20827bf80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
            /usr/src/go/src/bufio/bufio.go:132 +0xf0
    net/http.(*persistConn).readLoop(0xc20807a630)
            /usr/src/go/src/net/http/transport.go:842 +0xa4
    created by net/http.(*Transport).dialConn
            /usr/src/go/src/net/http/transport.go:660 +0xc9f

    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            /usr/src/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by adejoux** [comment]
Hello,

Is it possible to attach the nmon file used here or send it to me by email for me to test.

I improved checks in version **0.7.0** and **0.8.0** so you can try one of this versions too if you want.

Thanks,

Alain

**Comment by rmoff** [comment]
Same error with 0.8. I'll email you you logfile

**Comment by adejoux** [comment]
Thanks. It was a bug in TOP import. I only tested it when WLM was used without it the line contains one less elements. I fixed it and improved the check. I tested and now I can import your file.

**Comment by rmoff** [comment]
:+1: confirmed fixed. Thanks!
