### ISSUE TITLE
crash when the HMC cannot get system PCM data

### ISSUE THREAD

**Issue by adejoux** [adejoux/nmon2influxdb#40]
nmon2influxdb crash when the HMC cannot get properly the system statistics.

You see this message in the JSON data:

```json
	"sampleType": "ManagedSystem",
				"sampleInfo": {
					"timeStamp": "2017-01-04T08:32:30-0500",
					"status": 1,
					"errorInfo": [
						{
							"errId": "4002",
							"errMsg": "Processing did not happen because of error in managed system's LTM collection",
							"uuid": "067fe31c-d3d5-314a-a065-ec216a49d9c2",
							"reportedBy": "ManagedSystem",
							"occurrenceCount": 1
						}
					]
				}
			}
````

And the error is:

````
nmon2influxdb hmc import -m system1
Using configuration file /Users/adejoux/.nmon2influxdb.cfg
Updating  autogen retention policy to keep only the last 40d days. Timestamp based.
Fetching latest 2 hours performance metrics. See hmc_samples parameter.
Getting list of managed systems

system1

goroutine 1 [running]:
panic(0x3d8220, 0xc420012110)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/adejoux/nmon2influxdb/hmc.Import(0xc4201a0500)
	/Users/adejoux/go/src/github.com/adejoux/nmon2influxdb/hmc/import.go:68 +0x7757
github.com/codegangsta/cli.Command.Run(0x457df1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x45d546, 0x13, 0x0, ...)
	/Users/adejoux/go/src/github.com/codegangsta/cli/command.go:174 +0xbbe
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4201a0280, 0xc4201a0140, 0x0, 0x0)
	/Users/adejoux/go/src/github.com/codegangsta/cli/app.go:298 +0x9f8
github.com/codegangsta/cli.Command.startApp(0x456d4d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x45acc5, 0xd, 0x0, ...)
	/Users/adejoux/go/src/github.com/codegangsta/cli/command.go:249 +0x564
github.com/codegangsta/cli.Command.Run(0x456d4d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x45acc5, 0xd, 0x0, ...)
	/Users/adejoux/go/src/github.com/codegangsta/cli/command.go:65 +0x16a3
github.com/codegangsta/cli.(*App).Run(0xc4201a0000, 0xc42000c190, 0x5, 0x5, 0x0, 0x0)
	/Users/adejoux/go/src/github.com/codegangsta/cli/app.go:187 +0xa0c
main.main()
	/Users/adejoux/go/src/github.com/adejoux/nmon2influxdb/main.go:286 +0x20e6
````

I asked HMC developers what are the erro codes to watch.

**Comment by adejoux** [comment]
fixed in 2.1.1
